NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include # не забываем импортировать include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Подключаем наше приложение и не забываем создать urls.py в приложении/папке
    path('', include('newapp.urls')),# делаем так, чтобы все адреса из нашего приложения  сами автоматически подключались когда мы их добавим.
    path('sign/', include('sign.urls')),
    path('protect/', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
]

newapp/urls.py
from django.urls import path, include
from .views import PostList, PostDetail, News, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'newapp'
urlpatterns = [
    path('', PostList.as_view(), name='news'), # т.к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого вызываем метод as_view
    path('<int:pk>', PostDetail.as_view(), name='new_detail'),  # pk — это первичный ключ
    path('search/', News.as_view(), name='search'),  # Не забываем добавить эндпойнт для нового класса-представления.
    path('new/create/', PostCreateView.as_view(), name='new_create'),
    path('new/update/<int:pk>/', PostUpdateView.as_view(), name='new_update'),
    path('new/delete/<int:pk>/', PostDeleteView.as_view(), name='new_delete'),

]

sign/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'sign'
urlpatterns = [
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('signup/', RegisterView.as_view(), name='signup'),

]

newapp/models.py
from audioop import reverse

from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        allCommentRat = Comment.objects.filter(commentPost__author=self).aggregate(allCommentRating=Sum('rating')).get('rating__sum')
        aRat = 0
        aRat += allCommentRat.get('allCommentRating')

        self.ratingAuthor = pRat*3 + cRat + aRat
        self.save()

    def __str__(self):
        return self.authorUser.username

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...'

    def get_category_type(self):
        return self.get_categoryType_display()

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return reverse('newapp:new_detail', args=(self.pk,))

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)


    def __str__(self):
        try:
            return self.commentPost.author.authorUser.username
        except:
            return self.commentUser.username
    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

newapp/forms.py
from django.forms import ModelForm

from .models import Post
from django import forms

# Создаём модельную форму
class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['author', 'title', 'categoryType', 'text']
        widgets = {
            'author': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите имя автора',
          }),
          'title' : forms.TextInput(attrs={
            'class': 'form-control',
          }),
          'categoryType' : forms.Select(attrs={
            'class': 'form-control',
          }),
          'text' : forms.Textarea(attrs={
            'class': 'form-control',
          }),
        }
        labels={
            'author':'Автор',
            'title':'Заголовок',
            'categoryType':'Категория',
            'text':'Текст',
        }

newapp/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView # импоритируем необходимые дженерики
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import TemplateView

from .models import Post, Author
from datetime import datetime
from django.utils import timezone
from django.shortcuts import render
from django.views import View
from django.db.models import QuerySet
from django.core.paginator import Paginator # Импортируем класс, позволяющий удобно осуществлять постраничный вывод
from .filters import PostFilter # импортируем недавно написанный фильтр
from .forms import PostForm # импортируем нашу форму

class PostList(ListView):
    model = Post  # указываем модель, объекты которой мы будем выводить
    template_name = 'newapp/news.html'  # указываем имя шаблона, в котором будет лежать HTML, в нём будут все инструкции о том, как именно пользователю должны вывестись наши объекты
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты, его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    #queryset = Post.objects.order_by('-dateCreation')
   # ordering = ['-dateCreation']  # сортировка по дате в порядке убывания
    paginate_by = 10

    def get_queryset(self) -> QuerySet(any):
        post_filter = PostFilter(self.request.GET, queryset=Post.objects.all())
        return post_filter.qs.order_by('-dateCreation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now()) # добавим переменную текущей даты time_now
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST) # создаём новую форму, забиваем в неё данные из POST-запроса
        if form.is_valid(): # если пользователь ввёл всё правильно и нигде не накосячил, то сохраняем новый товар
            form.save()
        return super().get(request, *args, **kwargs)

class PostDetail(DetailView):
    model = Post
    template_name = 'newapp/new_detail.html'
    context_object_name = 'news'
    queryset = Post.objects.all()

class News(View):

    def get(self, request):
        news = Post.objects.order_by('-dateCreation')
        p = Paginator(news, 1)  # Создаём объект класса пагинатор, передаём ему список наших товаров и их количество для одной страницы
        news = p.get_page(
            request.GET.get('page', 1))  # Берём номер страницы из get-запроса. Если ничего не передали, будем показывать первую страницу
        # Теперь вместо всех объектов в списке товаров хранится только нужная нам страница с товарами

        data = {
            'news': news,
        }

        return render(request, 'newapp/search.html', data)

class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'newapp/new_create.html'
    form_class = PostForm
    context_object_name = 'news'

    def form_valid(self, form):
        author_name = form.cleaned_data['author']

        author, created = Author.objects.get_or_create(name=author_name)

        form.instance.author = author

        return super().form_valid(form)

    # дженерик для редактирования объекта
class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'newapp/new_create.html'
    form_class = PostForm
    context_object_name = 'news'

        # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)

    # дженерик для удаления товара
class PostDeleteView(DeleteView):
    template_name = 'newapp/new_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('newapp:news')
    context_object_name = 'news'

newapp/templates/newapp/default.html
{% extends 'layout/base.html' %} 
 

{% block title %}
news
{% endblock title %}
 
{% block content %}
<h1>Все новости</h1>
{{ default }}
{% endblock content %}

newapp/templates/newapp/new.html
{% extends 'layout/base.html' %}
{% load custom_filters %}
 
{% block title %}
New
{% endblock title %}
 
{% block content %}
  <table class="table">
    <tr>
        <th scope="col">
            Заголовок
        </th>
         <th scope="col">
            Дата
        </th>
        <th scope="col">
            Новость
        </th>
    </tr>
    <tr>
        <td>
            {{ new.title|safe|censor }}
        </td>
        <td>
            {{ new.dateCreation }}
        </td>
        <td>
            {{ new.text|censor }}
        </td>
    </tr>
  </table>
{% endblock content %}

newapp/templates/newapp/new_create.html
{% extends 'layout/base.html' %}
{% block title %}
  New create
{% endblock title %}

{% block content %}

<h3>Страница редактирования новости/статьи</h3>

<form method="POST">
  {% csrf_token %} {{ form }}
  <!-- Теперь нам нужна только готовая форма и кнопка -->
  <input class="btn btn-success my-3" type="submit" value="Add" />
</form>

{% endblock content %}

newapp/templates/newapp/new_delete.html
{% extends 'layout/base.html' %} 
{% block title %} 
  New delete
{% endblock title %} 

{% block content %}

<h3>Удалить новость/статью?</h3>
<div class="card">
  <div class="card-header">
    <h4>{{ news.title }}</h4>
    <div>
      Автор: <span class="badge bg-info">{{ news.author }}</span> Тип:
      <span class="badge bg-info">{{ news.get_categoryType_display }}</span>
    </div>
  </div>
  <div class="card-body">{{ news.text }}</div>
</div>
<form method="POST">
  {% csrf_token %}
  <input class="btn btn-danger my-3" type="submit" value="Удалить" />
</form>

{% endblock content %}

newapp/templates/newapp/new_detail.html
{% extends 'layout/base.html' %} 
{% block title %} 
  New
{% endblock title %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h3>{{ news.title }}</h3>
    <div>
      Автор: <span class="badge bg-info">{{ news.author }}</span>
      Тип: <span class="badge bg-info">{{ news.get_categoryType_display }}</span>
    </div>
  </div>
  <div class="card-body">{{ news.text }}</div>
</div>
<a href="{% url 'newapp:news' %}" class="btn btn-primary my-3">На главную</a>

{% endblock content %}

newapp/templates/newapp/news.html
{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}

<h1>Все новости</h1>
{% if news %}

<h3>{{ time_now }}</h3>
<!-- Здесь мы применяем фильтр date. Он очень похож на метод strftime у даты. С его помощью мы можем выводить дату в нужном нам формате -->
<!-- <a href="{% url 'newapp:search' %}" class="btn btn-primary my-3">Найти новость/статью</a> -->
<form method="GET">
   {{ filter.form }}
   <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
   <input class="btn btn-primary" type="submit" value="Найти">
</form>

<table class="table">
    <tr>
        <th scope="col">
            Автор
        </th>
        <th scope="col">
            Заголовок
        </th>
         <th scope="col">
            Дата
        </th>
        <th scope="col">
            Новость
        </th>


    </tr>
    {% for new in news %}
    <tr>
        <td>
            <a href="{% url 'newapp:new_detail' new.id %}">
            {{ new.author|safe }}
            </a>
        </td>
        <td>
            {{ new.title|safe|censor }}
        </td>
        <td>
            {{ new.dateCreation|date:"d-M-Y H:i" }}
        </td>
        <td>
            {{ new.text|truncatechars:50|censor }}
        </td>
    <td>
       <a href="{% url 'newapp:new_update' new.id %}">
           Редактировать
       </a>
       <a href="{% url 'newapp:new_delete' new.id %}">
           Удалить
       </a>
   </td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'newapp:new_create' %}" class="btn btn-primary my-3">Добавить новость/статью</a>
{% include 'newapp/parts/paginator.html' %}
{% else %}
<!-- Если новостей нет, то сообщаем об этом пользователю  -->
<h2>Новостей нет</h2>
{% endif %}
<div><a href="{% url 'sign:login' %}" class="btn btn-primary my-3">Войти</a>
<a href="{% url 'sign:logout' %}" class="btn btn-danger my-3">Выйти</a></div>
{% endblock content %}

newapp/templates/newapp/search.html
{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}

<h1>Все новости</h1>

<form method="GET">
   {{ filter.form }}
   <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
   <input class="btn btn-primary" type="submit" value="Найти">
</form>



{% endblock content %}