NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include # не забываем импортировать include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Подключаем наше приложение и не забываем создать urls.py в приложении/папке
    path('', include('newapp.urls')),# делаем так, чтобы все адреса из нашего приложения  сами автоматически подключались когда мы их добавим.
    path('sign/', include('sign.urls')),
    path('protect/', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
]

newapp/urls.py
from django.urls import path, include
from .views import PostList, PostDetail, News, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'newapp'
urlpatterns = [
    path('', PostList.as_view(), name='news'), # т.к. сам по себе это класс, то нам надо представить этот класс в виде view. Для этого вызываем метод as_view
    path('<int:pk>', PostDetail.as_view(), name='new_detail'),  # pk — это первичный ключ
    path('search/', News.as_view(), name='search'),  # Не забываем добавить эндпойнт для нового класса-представления.
    path('new/create/', PostCreateView.as_view(), name='new_create'),
    path('new/update/<int:pk>/', PostUpdateView.as_view(), name='new_update'),
    path('new/delete/<int:pk>/', PostDeleteView.as_view(), name='new_delete'),

]

sign/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'sign'
urlpatterns = [
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('signup/', RegisterView.as_view(), name='signup'),

]

templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'newapp:news' %}" class="nav-link px-2 text-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
        <li><a href="#" class="nav-link px-2 text-white">News</a></li>
        <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 text-white">About</a></li>
      </ul>

      <div class="text-end">
        <button type="button" class="btn btn-outline-light me-2">Login</button>
        <button type="button" class="btn btn-warning">Sign-up</button>
      </div>
    </div>
  </div>
</header>